<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HA1101901716" name="AAM-07.0.0.0.441-e55-0.ova" tests="8" failures="1" timestamp="23 Oct 2015 07:43:51 GMT" time="1298.319" errors="0">
  <testcase name="AddVMSuite" time="578.763" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="EditVM" time="43.646" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="StopVM" time="109.982" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="StartVM" time="137.933" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="RefreshVM" time="153.182" classname="com.avaya.sdmclient.runnerdemo.SecondThread">
    <failure type="com.avaya.sdmclient.extraResources.MyException" message="Operation Timed out... ">
      <![CDATA[com.avaya.sdmclient.extraResources.MyException: Operation Timed out... 
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1593)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1586)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1560)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1586)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1560)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1586)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1560)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1586)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1560)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1586)
	at com.avaya.sdmclient.Settings.checkSuccessOrFailure(Settings.java:1560)
	at com.avaya.sdmclient.runnerdemo.SecondThread.RefreshVM(SecondThread.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- RefreshVM -->
  <testcase name="RestartVM" time="143.597" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="DeleteVM" time="76.608" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
  <testcase name="startNewThread" time="54.478" classname="com.avaya.sdmclient.runnerdemo.SecondThread"/>
</testsuite> <!-- AAM-07.0.0.0.441-e55-0.ova -->
